### ISSUE TITLE
Update scripts for V3 of CF API 

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-scripts#142]
Some scripts include `/v2/` endpoints, and should be replaced with comparable `/v3/` endpoints since V2 is being deprecated.

**Comment by mheadd** [comment]
activate-org.sh
cf-audit.py
cf-create-org.sh
cf-create-user.sh
get-bucket-sizes-for-org.sh
suspend-org.sh
audit/cf-services-for-broker.sh
audit/get-sandbox-user-emails.sh

**Comment by JohnGMullen** [comment]
activate-org.sh at master is presently at v3

**Comment by ccostino** [comment]
Yes, both the activate and suspend org scripts were updated to V3-only calls recently.  I updated the description to remove them from the list.

**Comment by ccostino** [comment]
@cloud-gov/platform-ops and @pburkholder, we have a question regarding the [cf-audit.py](https://github.com/cloud-gov/cg-scripts/blob/master/cf-audit.py) script:  the API changed between V2 and V3 and you no longer pull all events, it has been split out into [audit events](http://v3-apidocs.cloudfoundry.org/version/3.93.0/#audit-events), [service usage events](http://v3-apidocs.cloudfoundry.org/version/3.93.0/#service-usage-events) and [app usage events](http://v3-apidocs.cloudfoundry.org/version/3.93.0/#app-usage-events).

Should we stick with just the audit events, as they are the primary mapping to the older V2 events endpoint, or do we need all 3?  Would it be helpful to include a parameter in this script to pick and choose?  The only issue there is that the processing of the results would have to be expanded on a bit as the output is different between each resource endpoint (for instance, only audit events have an actor and target).

If we stick with just the audit events, the updates to that script become easier as it's just accounting for the query parameter changes and adjusting how to filter the actor after retrieval.

**Comment by kwadwok15** [comment]
PR created for cf-audit.py updates

**Comment by ccostino** [comment]
PR approved!  I changed the list above into a checklist so we can mark things off as we complete them and this work is picked up again in the future.

**Comment by mheadd** [comment]
The `/v2` reference in `cf-create-user.sh` was a false positive.

**Comment by mheadd** [comment]
For `audit/get-sandbox-user-emails.sh` there does not appear to be an equivalent to `/v2/organizations/:guid:/users` in the V3 API. Nothing in the organizations endpoint or user endpoint seems to allow listing all users in a specific organization. As such, we may need to deprecate this script and find another way to export users in sandbox orgs.

**Comment by mheadd** [comment]
☝️ I broke out the remaining items in the list above to separate issues as each is probably a non-trivial amount of time to complete.
