### ISSUE TITLE
Update cf-create-org script for V3 of the CF API

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-scripts#155]
This [script](https://github.com/cloud-gov/cg-scripts/blob/master/cf-create-org.sh) makes a call to V2 of the CF API, and uses [a workaround detailed here](https://github.com/cloudfoundry/cli/issues/781). It may not be possible to replicate this workaround in V3 of the API and alternate approaches may need to be explored.

Issue spawned from #142.

**Comment by kwadwok15** [comment]
script updated to use v3 API call, awaiting PR review

**Comment by kwadwok15** [comment]
PR has been approved and merged. Ticket can be closed.
