### ISSUE TITLE
Update get-bucket-sizes-for-org script to use V3 of the CF API

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-scripts#156]
This [script](https://github.com/cloud-gov/cg-scripts/blob/master/get-bucket-sizes-for-org.sh) makes calls to V2 of the CF API and needs to be updated to use V3.

Issue spawned from #142.

**Comment by kwadwok15** [comment]
updated script and did a draft PR. 

Action Items: 

- Test changes 
- updated script if needed
- do a final PR and merge 
- close ticket

**Comment by kwadwok15** [comment]
Script updated, PR created awaiting review
