### ISSUE TITLE
Script to add/remove pages users

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cg-scripts#159]
The process will be manual at first. We need to be able to add/remove users from the pages.admin and pages.user groups in UAA.

--- 

## Security considerations

The above scopes are arbitrary strings used to denote Pages accounts in UAA. They have no impact on security except in the Pages app.

**Comment by kwadwok15** [comment]
@spgreenberg  clarification, are the user existing users or new users when adding them to the groups?
